import { useEffect, useMemo, useState } from "react";
import { ModeSwitch } from "./mode-switch";
import type { RatingResult } from "../types/rating";

type BracketMatch = { id: string; players: [string, string]; scores: [string, string] };
type BracketState = { matches: BracketMatch[]; ratingRecorded: boolean; tournamentId: string };
type Route = { from: string; outcome: "winner" | "loser"; to: string; slot: 0 | 1 };
type BracketBoardProps = { isOverlay: boolean; onRecordRating: (results: RatingResult[]) => void; onShowDraft: () => void; onShowRating: () => void; onShowRoster: () => void };

const STORAGE_KEY = "mk1-tournament-bracket:v1";
const openingIds = ["upper-1", "upper-2", "upper-3", "upper-4"];
const initialMatches: BracketMatch[] = [
  { id: "upper-1", players: ["Игрок 01", "Игрок 02"], scores: ["", ""] }, { id: "upper-2", players: ["Игрок 03", "Игрок 04"], scores: ["", ""] },
  { id: "upper-3", players: ["Игрок 05", "Игрок 06"], scores: ["", ""] }, { id: "upper-4", players: ["Игрок 07", "Игрок 08"], scores: ["", ""] },
  { id: "upper-5", players: ["", ""], scores: ["", ""] }, { id: "upper-6", players: ["", ""], scores: ["", ""] }, { id: "upper-7", players: ["", ""], scores: ["", ""] },
  { id: "lower-1", players: ["", ""], scores: ["", ""] }, { id: "lower-2", players: ["", ""], scores: ["", ""] }, { id: "lower-3", players: ["", ""], scores: ["", ""] },
  { id: "lower-4", players: ["", ""], scores: ["", ""] }, { id: "lower-5", players: ["", ""], scores: ["", ""] }, { id: "lower-6", players: ["", ""], scores: ["", ""] },
  { id: "grand-final", players: ["", ""], scores: ["", ""] },
];
const routes: Route[] = [
  { from: "upper-1", outcome: "winner", to: "upper-5", slot: 0 }, { from: "upper-1", outcome: "loser", to: "lower-1", slot: 0 }, { from: "upper-2", outcome: "winner", to: "upper-5", slot: 1 }, { from: "upper-2", outcome: "loser", to: "lower-1", slot: 1 },
  { from: "upper-3", outcome: "winner", to: "upper-6", slot: 0 }, { from: "upper-3", outcome: "loser", to: "lower-2", slot: 0 }, { from: "upper-4", outcome: "winner", to: "upper-6", slot: 1 }, { from: "upper-4", outcome: "loser", to: "lower-2", slot: 1 },
  { from: "upper-5", outcome: "winner", to: "upper-7", slot: 0 }, { from: "upper-5", outcome: "loser", to: "lower-3", slot: 1 }, { from: "upper-6", outcome: "winner", to: "upper-7", slot: 1 }, { from: "upper-6", outcome: "loser", to: "lower-4", slot: 1 },
  { from: "lower-1", outcome: "winner", to: "lower-3", slot: 0 }, { from: "lower-2", outcome: "winner", to: "lower-4", slot: 0 }, { from: "lower-3", outcome: "winner", to: "lower-5", slot: 0 }, { from: "lower-4", outcome: "winner", to: "lower-5", slot: 1 },
  { from: "lower-5", outcome: "winner", to: "lower-6", slot: 0 }, { from: "upper-7", outcome: "loser", to: "lower-6", slot: 1 }, { from: "upper-7", outcome: "winner", to: "grand-final", slot: 0 }, { from: "lower-6", outcome: "winner", to: "grand-final", slot: 1 },
];

function createTournamentId() { return `bracket-${Date.now().toString(36)}-${Math.random().toString(36).slice(2, 8)}`; }
function createInitialState(): BracketState { return { matches: initialMatches.map((match) => ({ ...match, players: [...match.players], scores: [...match.scores] } as BracketMatch)), ratingRecorded: false, tournamentId: createTournamentId() }; }
function readBracketState(): BracketState { try { const stored = JSON.parse(localStorage.getItem(STORAGE_KEY) ?? "null") as BracketState | null; if (stored && Array.isArray(stored.matches) && stored.matches.length === initialMatches.length) return { matches: stored.matches, ratingRecorded: Boolean(stored.ratingRecorded), tournamentId: stored.tournamentId || createTournamentId() }; } catch { /* use clean bracket */ } return createInitialState(); }
function isCompleteMatch(match: BracketMatch) { const [first, second] = match.scores.map(Number); return Boolean(match.players[0].trim() && match.players[1].trim() && match.scores[0] !== "" && match.scores[1] !== "" && first !== second); }
function resultPlayer(match: BracketMatch, kind: Route["outcome"]) { if (!isCompleteMatch(match)) return ""; const winner = Number(match.scores[0]) > Number(match.scores[1]) ? match.players[0] : match.players[1]; return kind === "winner" ? winner : winner === match.players[0] ? match.players[1] : match.players[0]; }
function reconcile(matches: BracketMatch[]) { const next = matches.map((match) => ({ ...match, players: [...match.players], scores: [...match.scores] } as BracketMatch)); const find = (id: string) => next.find((match) => match.id === id)!; routes.forEach((route) => { const destination = find(route.to); const value = resultPlayer(find(route.from), route.outcome); if (destination.players[route.slot] !== value) { destination.players[route.slot] = value; destination.scores[route.slot] = ""; } }); return next; }

function MatchCard({ disabled, editablePlayers, match, onChange }: { disabled: boolean; editablePlayers: boolean; match: BracketMatch; onChange: (id: string, row: 0 | 1, field: "player" | "score", value: string) => void }) {
  const canEnterScores = !disabled && Boolean(match.players[0].trim() && match.players[1].trim());
  return <div className="bracket-match">{([0, 1] as const).map((row) => <div className="bracket-match__row" key={row}><input aria-label={`Ник игрока ${row + 1}`} disabled={disabled || !editablePlayers} placeholder="Ник игрока" value={match.players[row]} onChange={(event) => onChange(match.id, row, "player", event.target.value)} /><input aria-label={`Счёт игрока ${row + 1}`} className="bracket-match__score" disabled={!canEnterScores} inputMode="numeric" maxLength={2} placeholder="–" value={match.scores[row]} onChange={(event) => onChange(match.id, row, "score", event.target.value.replace(/[^0-9]/g, ""))} /></div>)}</div>;
}

export function BracketBoard({ isOverlay, onRecordRating, onShowDraft, onShowRating, onShowRoster }: BracketBoardProps) {
  const [state, setState] = useState<BracketState>(readBracketState); const [isResetConfirming, setIsResetConfirming] = useState(false);
  const completeMatches = useMemo(() => state.matches.filter(isCompleteMatch), [state.matches]); const canRecord = completeMatches.length === state.matches.length && !state.ratingRecorded;
  useEffect(() => { localStorage.setItem(STORAGE_KEY, JSON.stringify(state)); }, [state]);
  function updateMatch(id: string, row: 0 | 1, field: "player" | "score", value: string) { if (state.ratingRecorded) return; setState((current) => { const matches = current.matches.map((match) => { if (match.id !== id) return match; const next = { ...match, players: [...match.players] as [string, string], scores: [...match.scores] as [string, string] }; if (field === "player") { next.players[row] = value; next.scores[row] = ""; } else next.scores[row] = value; return next; }); return { ...current, matches: reconcile(matches) }; }); }
  function recordTournament() { if (!canRecord) return; const playedAt = new Date().toISOString(); const month = playedAt.slice(0, 7); onRecordRating(completeMatches.map((match) => ({ sourceId: `${state.tournamentId}:${match.id}`, playedAt, month, winner: resultPlayer(match, "winner").trim(), loser: resultPlayer(match, "loser").trim() }))); setState((current) => ({ ...current, ratingRecorded: true })); }
  function resetTournament() { if (!isResetConfirming) { setIsResetConfirming(true); return; } setState(createInitialState()); setIsResetConfirming(false); }
  const byId = (id: string) => state.matches.find((match) => match.id === id)!; const props = (id: string) => ({ disabled: state.ratingRecorded, editablePlayers: openingIds.includes(id), match: byId(id), onChange: updateMatch });
  return <><header className="bracket-header"><div><p className="page-eyebrow">ELKAMUSAEV EVENTS CENTR</p><h1 className="page-title">ТУРНИРНАЯ СЕТКА</h1></div></header>{!isOverlay && <div className="page-mode-row"><ModeSwitch activeMode="bracket" onChange={(mode) => { if (mode === "roster") onShowRoster(); if (mode === "draft") onShowDraft(); if (mode === "rating") onShowRating(); }} /><div className="bracket-tournament-actions"><button disabled={!canRecord} title={canRecord ? "" : "Заполните результаты всех матчей сетки"} type="button" onClick={recordTournament}>{state.ratingRecorded ? "ТУРНИР УЧТЕН" : "ЗАВЕРШИТЬ ТУРНИР"}</button>{state.ratingRecorded ? <button className={`is-reset ${isResetConfirming ? "is-confirming" : ""}`} type="button" onClick={resetTournament}>{isResetConfirming ? "ПОДТВЕРДИТЬ НОВУЮ СЕТКУ" : "НОВАЯ СЕТКА"}</button> : null}</div></div>}<section className="bracket-grid bracket-grid--top8" aria-label="Турнирная сетка Top 8"><div className="bracket-lane bracket-lane--upper bracket-lane--top8"><div className="bracket-column bracket-column--opening"><MatchCard {...props("upper-1")} /><MatchCard {...props("upper-2")} /><MatchCard {...props("upper-3")} /><MatchCard {...props("upper-4")} /></div><div className="bracket-column bracket-column--middle"><MatchCard {...props("upper-5")} /><MatchCard {...props("upper-6")} /></div><div className="bracket-column bracket-column--final"><MatchCard {...props("upper-7")} /></div><div className="bracket-column bracket-column--grand"><MatchCard {...props("grand-final")} /></div></div><div className="bracket-divider" /><div className="bracket-lane bracket-lane--lower bracket-lane--top8"><div className="bracket-column bracket-column--opening"><MatchCard {...props("lower-1")} /><MatchCard {...props("lower-2")} /></div><div className="bracket-column bracket-column--middle"><MatchCard {...props("lower-3")} /><MatchCard {...props("lower-4")} /></div><div className="bracket-column bracket-column--final"><MatchCard {...props("lower-5")} /></div><div className="bracket-column bracket-column--grand"><MatchCard {...props("lower-6")} /></div></div></section></>;
}
